### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by acelaya** [zf-hipsters/bootstrap-flash-messenger#1]
The idea of this module looks good, but I am affraid it does not work.

The first I've seen is that the controller plugin has this namespace.

``` php
namespace FlashMessenger\View\Helper;
```

Insetad of

``` php
namespace FlashMessenger\Controller\Plugin;
```

So an error is thrown when you try to use it, because the autoloader is not able to find the class.
Also, it is extending `Zend\View\Helper\AbstractHelper` instead of `Zend\Mvc\Controller\Plugin\AbstractPlugin`.

But once that is solved the view helper does not print anything, I am not sure why.

However I insist that the idea is very good. I have forked it and I was planning to add support to titles (I have seen they are hardcoded in the views) and icons (both glyphicons and font awesome icons)

**Comment by aweathe** [comment]
Yes let me fix that and add the requested changes. It'll be pushed in an
hour or so.

**Comment by acelaya** [comment]
Thanks!

**Comment by aweathe** [comment]
Okay, my bad I'd overwritten the helper with an older version. All fixed and I've updated the readme regarding how easy it is to modify the default templates! Let me know how it works for you! If you have any other suggestions, please let me know.

**Comment by acelaya** [comment]
Now it's working.
Thank you.

**Comment by arthasmx** [comment]
working ?

so, why is this issue still open ?

**Comment by dkcwd** [comment]
Thanks @arthasmx  
Closing for now as issue appears to be resolved.
